### ISSUE TITLE
TypeError: inNodes.map(...).flat is not a function

### ISSUE THREAD

**Issue by ReadingCommando** [backslash47/xslt#1]
TypeError: inNodes.map(...).flat is not a function                                                                           at steps.reduce (node_modules\xpath-ts\src\path-expr.ts:271:10)                                                             at Array.reduce ()                                                                                               at Function.applySteps (node_modules\xpath-ts\src\path-expr.ts:266:18)                                                      at Function.applyLocationPath (node_modules\xpath-ts\src\path-expr.ts:22:2                                            1)
--

**Comment by backslash47** [comment]
Hi, could you share the setup in which you try to use the library? (browser/nodejs, using webpack/rollup, ...)

**Comment by ToryLawson** [comment]
I had this issue on Node 10.13 and again on 10.15, but it disappeared once I upgraded to 11.11, if that helps. Array.prototype.flat() has only [recent support in many browsers](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flat#Browser_compatibility), so that makes sense.

**Comment by backslash47** [comment]
Thanks for reporting and investigating the issue.

Array.prototype.flat is indeed supported from NodeJS 11.x and up (https://node.green/#ES2019-features-Array-prototype--flat--flatMap--Array-prototype-flat).

So I modified the README accordingly.
