### ISSUE TITLE
 Cannot read property 'length' of null

### ISSUE THREAD

**Issue by edamazzio** [backslash47/xslt#2]
node_modules\xslt-ts\dist\xslt.js:351

Code goes as follows: 

`var xslt = require ('xslt-ts');
    
    var DOMParser = require('xmldom').DOMParser;
    var XMLSerializer = require('xmldom').XMLSerializer;
    var DOMImplementation = require('xmldom').DOMImplementation;

    var xmlDoc = new DOMParser().parseFromString(xmlString , 'text/xml');
    var xsltDoc = new DOMParser().parseFromString(xsltString , 'text/xml');
    
    xslt.install(new DOMParser(), new XMLSerializer(), new DOMImplementation());
    
    var outXmlString = xslt.xsltProcess(xmlDoc, xsltDoc);

    console.log(outXmlString);`

**Comment by mrMams** [comment]
Hello,

The problem comes from **here**:

```
function xsltChildNodes(input: XSLTContext, template: Node, output: Node) {
    // Clone input context to keep variables declared here local to the
    // siblings of the children.
    const context = input.clone();
    for (let i = 0; i < template.childNodes.length; ++i) { /* HERE : Fails when childNodes is null */
    if (isXmlDeclaration(template.childNodes[i])) {
      continue;
    }
    xsltProcessContext(context, template.childNodes[i], output);
  }
}
```

This issue happens when processing a node that meets all the following conditions:
* the node is not a text node
* the node is not an element
* the node has no child nodes 

This is the typically the case when the node is a comment. I didn't think about other node types for which this can happen (I'd need to do some research).

@edamazzio : you can see if you can derive some workaround from this (e.g. by removing comments from your XSLT file, for instance).
 @backslash47 : can you fix this ? I wouldn't mind making a pull request here, but I don't know when I can find enough time to work on it.

Hope this helps.

**Comment by backslash47** [comment]
Hi,

thanks for investigation.

I am currently focusing on different project. I might move back to this in couple of weeks, but if you are able the pull request, it would be awesome!

**Comment by backslash47** [comment]
I found some time to fix it.
